### ISSUE TITLE
Project Config (Similar to tsconfig or package.json)

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#163]
### Introducing the `'.jaclang-project'` or `'jaclang-config.json'` or `jaclang-config.yml`

What this brings to the language?
1. Project Setup (Project Name, Version, Dependancy/Plugin Management)
2. Scripts (Build Steps, Dev Run Steps etc.)
3. Build Settings (Import Mapping, Whether to include Python Code Gens etc.)

Example File (using JSON)
```json
{
    "project_name": "slam-tool",
    "version": "0.0.1",
    "author": "Jason Mars",
    "organization": "Jaseci Labs",
    "description": "LLM and SLM Benchmarking Tool for Real Usecases",
    "scripts": {
        "serve": "uvicorn query_engine:serv_actions && streamlit run app.py",
        "build": "echo 'build'"
    },
    "build": {
        "import_map": {
            "components": "./src/components",
            "actions": "./src/actions",
            "utils": "./src/utils"
        },
        "output_dir": "./build",
        "entry_points": "./src/app.jac",
        "gen_python": true
    },
    "dependacies": {
        "@jaclang/llm": "^0.0.1",
        "@jaclang/mojo": "0.0.1",
        "streamlit": "^0.82.0",
        "jaseci": "^0.0.1",
        "uvicorn": "^0.13.4"
    },
    "dev_dependencies": {
        "pytest": "^6.2.4",
        "@jaclang/debugger": "^0.0.1"
    }
}
```

Example File using YAML
```yaml
---
project_name: slam-tool
version: 0.0.1
author: Jason Mars
organization: Jaseci Labs
description: LLM and SLM Benchmarking Tool for Real Usecases
scripts:
  serve: uvicorn query_engine:serv_actions && streamlit run app.py
  build: echo 'build'
build:
  import_map:
    components: "./src/components"
    actions: "./src/actions"
    utils: "./src/utils"
  output_dir: "./build"
  entry_points: "./src/app.jac"
  gen_python: true
dependacies:
  "@jaclang/llm": "^0.0.1"
  "@jaclang/mojo": "0.0.1"
  streamlit: "^0.82.0"
  jaseci: "^0.0.1"
  uvicorn: "^0.13.4"
dev_dependencies:
  pytest: "^6.2.4"
  "@jaclang/debugger": "^0.0.1"
```

#### Using Imports after mapping
In the Current Jaclang we have to think about the relative import when running the files. for example assuming there is 3 files (`./src/utils.jac`, `./src/component.jac` and `./app.jac`)
```python
# ./src/component.jac
import:jac from utils, something # relative import
```
This wont work if the entry point is `app.jac` and this only works if the entry point is inside the `src` folder. In order to make it work code should be as follows.
```python
# ./src/component.jac
import:jac from src.utils, something
```
This is reasonable if the project is not big. But when the project is becoming bigger and more nested folders are getting created this is hard to manage. **(Huge issue in python)**

So by introducing the **import_mapping --> keywords mapped to absolute locations** we can mitigate this. example code would be like follows.
```python
# ./src/component.jac
import:jac from @src.utils, something
```
